<?php

$title = "Add grade";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$grade = $this->form->get('grade');
$value = $grade->get('value');
$value->setAttribute('class', 'form-control');
$value->setAttribute('placeholder', 'Grade');

$wage = $grade->get('wage');
$wage->setAttribute('class', 'form-control');
$wage->setAttribute('placeholder', 'Wage');

$course = $grade->get('course');
$course->setAttribute('id', 'course-select');
$course->setAttribute('class', 'form-control');
$courseOptions = [];
foreach ($this->courses as $data) :
    $courseOptions[$data['id']] = $data['name'];
endforeach;
$course->setValueOptions($courseOptions);
//$course->setEmptyOption('Select course');

$student = $grade->get('student');
$student->setAttribute('id', 'student-select');
$student->setAttribute('class', 'form-control');
//$student->setEmptyOption('Select student');

//$studentCourse = $grade->get('studentCourse');
//$studentCourse->setAttribute('id', 'student-course-select');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('grade', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="form-group">
    <?= $this->formLabel($value) ?>
    <?= $this->formElement($value) ?>
    <?= $this->formElementErrors()->render($value, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($wage) ?>
    <?= $this->formElement($wage) ?>
    <?= $this->formElementErrors()->render($wage, ['class' => 'help-block']) ?>
</div>

<!--<div class="form-group">-->
<!--    <label for="course-select">Course</label>-->
<!--    <select id="course-select" class="form-control">-->
<!--        <option value="" selected="selected">Select course</option>-->
<!--        --><?php //foreach ($courses as $data) :?>
<!--            <option value="--><?php //= $data['id']; ?><!--">-->
<!--                --><?php //= $data['name']; ?>
<!--            </option>-->
<!--        --><?php //endforeach; ?>
<!--    </select>-->
<!--</div>-->
<!---->
<!--<div class="form-group">-->
<!--    <label for="student-select">Student</label>-->
<!--    <select id="student-select" class="form-control">-->
<!--        <option value="" selected="selected">Select student</option>-->
<!--    </select>-->
<!--</div>-->

<div class="form-group">
    <?= $this->formLabel($course) ?>
    <?= $this->formSelect($course) ?>
    <?= $this->formElementErrors()->render($course, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($student) ?>
    <?= $this->formSelect($student) ?>
    <?= $this->formElementErrors()->render($student, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($grade->get('id'));
//echo $this->formHidden($studentCourse);
echo $this->form()->closeTag($this->form);
?>

<script type="text/javascript">
    const courses = <?= json_encode($this->courses) ?>;
</script>
<script type="text/javascript" src="/js/updateStudentForm.js"></script>