<?php
/**
 * @var array<Grade> $grades
 */

use GradeBook\Entity\Grade;

$title = 'Grades';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('grade', ['action' => 'add']) ?>">Add new grade</a>
</p>

<table class="table">
    <tr>
        <th>Grade</th>
        <th>Wage</th>
        <th>Date of assessment</th>
        <th>Student</th>
        <th>Course</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($grades as $grade) : ?>
        <tr>
            <td><?= $this->escapeHtml($grade->getValue()) ?></td>
            <td><?= $this->escapeHtml($grade->getWage()) ?></td>
            <td><?= $this->escapeHtml($grade->getDate()->format('Y-m-d H:i:s')) ?></td>
            <td><?= $this->escapeHtml((fn($student) => $student->getFirstName() . ' ' . $student->getLastName())
                ($grade->getStudentCourse()->getStudent())) ?></td>
            <td><?= $this->escapeHtml($grade->getStudentCourse()->getCourse()->getName()) ?></td>
            <td>
                <a href="<?= $this->url('grade', ['action' => 'edit', 'id' => $grade->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('grade', ['action' => 'delete', 'id' => $grade->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>