<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$title = 'Delete admin';
$url   = $this->url('admin', ['action' => 'delete', 'id' => $this->id]);
$this->headTitle($title);
echo $this->partial('partial/menu.phtml');
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Are you sure you want to delete
    <?= $this->escapeHtml($this->admin->getFirstName()) ?>
    <?= $this->escapeHtml($this->admin->getLastName()) ?>?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $this->admin->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>
