<?php
/**
 * @var Admin $admin
 */

use GradeBook\Entity\Admin;

$title = 'Delete admin';
$url   = $this->url('admin', ['action' => 'delete', 'id' => $id]);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Are you sure you want to delete
    <?= $this->escapeHtml($admin->getFirstName()) ?>
    <?= $this->escapeHtml($admin->getLastName()) ?>?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $admin->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>
