<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Form\View\HelperTrait $this
 */
$title = "Edit admin";
$this->headTitle($title);
echo $this->partial('partial/menu.phtml');
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$admin = $this->form->get('admin');
$firstName = $admin->get('firstName');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', 'First name');

$lastName = $admin->get('lastName');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', 'Last name');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('admin', [
    'action' => 'edit',
    'id'     => $this->id,
]));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="form-group">
    <?= $this->formLabel($firstName) ?>
    <?= $this->formElement($firstName) ?>
    <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($lastName) ?>
    <?= $this->formElement($lastName) ?>
    <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($admin->get('id'));
echo $this->form()->closeTag();