<?php

$title = 'Admins';
$this->headTitle($title);
$this->partial('menu.phtml');
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin', ['action' => 'add']) ?>">Add new admin</a>
</p>

<table class="table">
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($admins as $admin) : ?>
        <tr>
            <td><?= $this->escapeHtml($admin->getFirstName()) ?></td>
            <td><?= $this->escapeHtml($admin->getLastName()) ?></td>
            <td>
                <a href="<?= $this->url('admin', ['action' => 'edit', 'id' => $admin->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('admin', ['action' => 'delete', 'id' => $admin->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>