<div>
    <ul>
        <li>
            <a href="<?= $this->url('admin') ?>">Admins</a>
        </li>
        <li>
            <a href="<?= $this->url('teacher') ?>">Teachers</a>
        </li>
        <li>
            <a href="<?= $this->url('student') ?>">Students</a>
        </li>
        <li>
            <a href="<?= $this->url('grade') ?>">Grades</a>
        </li>
        <li>
            <a href="<?= $this->url('course') ?>">Courses</a>
        </li>
        <li>
            <a href="<?= $this->url('studentCourse') ?>">Students - Courses</a>
        </li>
    </ul>
</div>