<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$title = 'Remove student from course';
$url   = $this->url('studentCourse', ['action' => 'delete', 'studentId' => $this->studentId, 'courseId' => $this->courseId]);
$this->headTitle($title);
echo $this->partial('partial/menu.phtml');
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Are you sure you want to remove <?= (fn($student) => $student->getFirstName() . ' ' . $student->getLastName())
    ($this->studentCourse->getStudent()) ?> from <?= $this->studentCourse->getCourse()->getName() ?>?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="studentId" value="<?= $this->studentCourse->getStudent()->getId() ?>" />
        <input type="hidden" name="courseId" value="<?= $this->studentCourse->getCourse()->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>