<?php

$title = 'Edit relationship between student and course';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$studentCourse = $this->form->get('studentCourse');

$course = $studentCourse->get('course');
$course->setAttribute('class', 'form-control');
$course->setAttribute('id', 'course-select');
$courseOptions = [];
foreach ($this->studentsCourses as $data):
    $courseOptions[$data['id']] = $data['name'];
endforeach;
$course->setValueOptions($courseOptions);

$student = $studentCourse->get('student');
$student->setAttribute('class', 'form-control');
$student->setAttribute('id', 'student-select');
$studentOptions = [$student->getValue() => $this->studentData->getFirstName() . ' ' . $this->studentData->getLastName()];
foreach ($this->studentsCourses[$course->getValue()]['students'/*'studentsCourse'*/] as /*$studentCourse*/$data):
    //$data = $studentCourse['student'];
    $studentOptions[$data['id']] = $data['firstName'] . ' ' . $data['lastName'];
endforeach;
$student->setValueOptions($studentOptions);

// This provides CSS classes for the submit button:
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('studentCourse', [
    'action'    => 'edit',
    'studentId' => $this->studentId,
    'courseId'  => $this->courseId,
]));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($course) ?>
    <?= $this->formElement($course) ?>
    <?= $this->formElementErrors()->render($course, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($student) ?>
    <?= $this->formSelect($student) ?>
    <?= $this->formElementErrors()->render($student, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag($this->form);
?>

<script type="text/javascript">
    const courses = <?= json_encode($this->studentsCourses) ?>;
</script>
<script type="text/javascript" src="/js/updateStudentForm.js"></script>