<?php

$title = 'Add new course';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$course = $form->get('course');
$name = $course->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$teacher = $course->get('teacher');
$teacher->setAttribute('class', 'form-control');
$teacher->setAttribute('placeholder', 'Teacher');
$options = [];
foreach ($teachers as $data) :
    $options[$data['id']] = $data['firstName'] . ' ' . $data['lastName'];
endforeach;
$teacher->setValueOptions($options);

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('course', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($teacher) ?>
        <?= $this->formSelect($teacher) ?>
        <?= $this->formElementErrors()->render($teacher, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($course->get('id'));
echo $this->form()->closeTag();