<?php

$title = "Edit course";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$course = $this->form->get('course');
$name = $course->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$teacher = $course->get('teacher');
$teacher->setAttribute('class', 'form-control');
$teacher->setAttribute('placeholder', 'Teacher');
$options = [];
foreach ($this->teachers as $data) :
    $options[$data['id']] = $data['firstName'] . ' ' . $data['lastName'];
endforeach;
$teacher->setValueOptions($options);

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('course', [
    'action' => 'edit',
    'id'     => $this->id,
]));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($teacher) ?>
        <?= $this->formSelect($teacher) ?>
        <?= $this->formElementErrors()->render($teacher, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($course->get('id'));
echo $this->form()->closeTag($this->form);