<?php
/**
 * @var CourseForm $form
 * @var array $teachers
 * @var int $id
 */

use GradeBook\Form\CourseForm;

$title = "Edit course";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$course = $form->get('course');
$name = $course->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$teacher = $course->get('teacher');
$teacher->setAttribute('class', 'form-control');
$teacher->setAttribute('placeholder', 'Teacher');
$options = [];
foreach ($teachers as $data) :
    $options[$data['id']] = $data['firstName'] . ' ' . $data['lastName'];
endforeach;
$teacher->setValueOptions($options);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('course', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($teacher) ?>
        <?= $this->formSelect($teacher) ?>
        <?= $this->formElementErrors()->render($teacher, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($course->get('id'));
echo $this->form()->closeTag($form);