<?php

$title = 'Courses';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('course', ['action' => 'add']) ?>">Add new course</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Teacher</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($courses as $course) : ?>
        <tr>
            <td><?= $this->escapeHtml($course->getName()) ?></td>
            <td><?= $this->escapeHtml((fn($teacher) => $teacher->getFirstName() . ' ' . $teacher->getLastName())
                ($course->getTeacher())) ?></td>
            <td>
                <a href="<?= $this->url('course', ['action' => 'edit', 'id' => $course->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('course', ['action' => 'delete', 'id' => $course->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>