<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Form\View\HelperTrait $this
 */
$title = 'Add new teacher';
$this->headTitle($title);
echo $this->partial('partial/menu.phtml');
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$teacher = $this->form->get('teacher');
$firstName = $teacher->get('firstName');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', 'First name');

$lastName = $teacher->get('lastName');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', 'Last name');

// This provides CSS classes for the submit button:
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('teacher', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($firstName) ?>
        <?= $this->formElement($firstName) ?>
        <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($lastName) ?>
        <?= $this->formElement($lastName) ?>
        <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($teacher->get('id'));
echo $this->form()->closeTag();