<?php

$title = "Edit teacher";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$teacher = $this->form->get('teacher');
$firstName = $teacher->get('firstName');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', 'First name');

$lastName = $teacher->get('lastName');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', 'Last name');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('teacher', [
    'action' => 'edit',
    'id'     => $this->id,
]));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
    <div class="form-group">
        <?= $this->formLabel($firstName) ?>
        <?= $this->formElement($firstName) ?>
        <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($lastName) ?>
        <?= $this->formElement($lastName) ?>
        <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($teacher->get('id'));
echo $this->form()->closeTag($this->form);